### ISSUE TITLE
Docker Demo available - Any plans to add seeds.rb?

### ISSUE THREAD

**Issue by fspc** [Loos/bike-database#4]
I have created a Docker image project for bike-database [https://github.com/fspc/bike-database](https://github.com/fspc/bike-database) and a demo at [ http://bike-database.wvcompletestreets.org]( http://bike-database.wvcompletestreets.org).

Do you have imminent plans to create a seed.rb so that initial default values can be committed to the database? 

-Jonathan

**Comment by Loos** [comment]
Hi Jonathan,

Thanks for creating a docker container! Right now I have no plans to create a seed.rb to seed initial values; at one point I had a seed file but it ended up being more effort to maintain than it was worth  for me.
